version: "3"

services:
  master:
    build: .
    # Add limited resources
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2g
    # fixed name for hostname resolution
    container_name: master
    environment:
      # used by entrypoint script to know this is master
      - NODE_ROLE=master
    volumes:
      - hpc-shared:/shared
      - ./benchmark:/benchmark
      - ./results/master:/tmp/benchmark-results
    networks:
      hpcnet:
        # Optional fixed IP for consistency
        ipv4_address: 172.28.1.10
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "22"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node configuration
  node-01:
    # use same Dockerfile for worker
    build: .
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2g
    container_name: node-01
    environment:
      - NODE_ROLE=worker
    volumes:
      - hpc-shared:/shared
      - ./benchmark:/benchmark
      - ./results/node-01:/tmp/benchmark-results
    networks:
      hpcnet:
        ipv4_address: 172.28.1.11
    depends_on:
      # ensure master starts first (for ordering)
      - master

  node-02:
    build: .
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2g
    container_name: node-02
    environment:
      - NODE_ROLE=worker
    volumes:
      - hpc-shared:/shared
      - ./benchmark:/benchmark
      - ./results/node-02:/tmp/benchmark-results
    networks:
      hpcnet:
        ipv4_address: 172.28.1.12
    depends_on:
      - master

# named volume used by all nodes for shared directory
volumes:
  hpc-shared:
    # This creates a shared volume accessible by all containers

# Define a bridge network with fixed IP range for predictable addressing
networks:
  hpcnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
