network:
  version: 2
  renderer: networkd # Specify to use systemd-networkd
  ethernets:
    enp0s8:
      dhcp4: true
    enp0s9:
      dhcp4: no
      addresses:
        - 192.168.56.1/24
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
